spring:
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/db-guest
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
server:
  port: 8084

file:
  upload:
    root: ${user.home}/Projects/xStay/upload-folder
    id-document-image: ${file.upload.root}/id-documents/:idDocumentId/images