spring:
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/db-guest
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
server:
  port: 8083

file:
  upload:
    root: ${user.home}/Projects/xStay/upload-folder
    unit-image: ${file.upload.root}/units/:unitId/images