spring:
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/db-guest
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8084

file:
  upload:
    identity-document: guests/:guestId/identity-documents/
